version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:2.6.0
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    restart: unless-stopped
    volumes:
      - "./data/:/pulsar/data"
  consumer:
    build:
      context: .
    command: npm run consumer
    volumes:
      - ".:/var/app"
    depends_on:
      - pulsar
  producer:
    build:
      context: .
    command: npm run producer
    volumes:
      - ".:/var/app"
    depends_on:
      - pulsar
  dashboard:
    image: apachepulsar/pulsar-manager:v0.2.0
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
